### PR TITLE
upgraded pushbuttonhhelper with micronaut 4.7.4

### PR DESCRIPTION
**Pull request by avaenk**
https://github.com/oss-slu/Pi4Micronaut/issues/317

What what changed:
I verified that the PushButtonHelper and DigitalInputConfiguration classes remain compatible with Micronaut 4.7.6. At the point there are no required code changed, as the classes do not directly depend on the Micronaut features that needed to be changed. Hardware testing was completed to ensure no functionalities changed with the update. 

Why it was changed:
Part of the Micronaut 4.7.6 upgraded all of these classes needed to be looked over to ensure compatibility. We needed to review the code to ensure that future updates do not bring undefined behavior.

How it was changed:
Reviewed PushButtonHelper and DigitalInputConfiguration for breaking changed in Micronaut 4.7.6, confirmed that all of the methods continue to be valid after the update. Ran with gradle and separate testing to ensure no compilation errors. Did not make any code changes for the time being. After testing hardware functionality remains the same post update so no code changes are needed. 

https://github.com/user-attachments/assets/bb59d0da-f9eb-4923-a275-ea6f76dedd22

Screenshot 2025-03-07 at 13 47 38

### CODE REVIEW

File: pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/PushButtonHelper.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import com.pi4j.io.gpio.digital.DigitalInput;
+import com.pi4j.io.gpio.digital.DigitalStateChangeListener;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+/**
+ * The PushButtonHelper class is used to create a listener that determines when a 4 pin button is pressed.
+ */
+public class PushButtonHelper {
+    private static final Logger log = LoggerFactory.getLogger(PushButtonHelper.class);
```
Comment (RalphTan37) [inline pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/PushButtonHelper.java:12]: Ava, great job on upgrading the PushButtonHelper class! I did something very similar with my helper class by using the keyword final for logger so it can ensure immutability.

**Review by yrlmanoharreddy — CHANGES_REQUESTED** [review]
Please perform hardware testing to verify if the PushButtonHelper class functions correctly after upgrading Micronaut to 4.7.6. Ensure that no dependencies are broken and that the component behaves as expected. Push the changes after confirming everything works as intended.

**Review by yrlmanoharreddy — APPROVED** [review]
The PushButtonHelper upgrade has been successfully completed and is ready for merge
